spring.application.name=ventas

spring.datasource.url=jdbc:h2:mem:ventasdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

server.port=8080

world-clock.url=http://worldclockapi.com/api/json/utc/now